// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23QwVV32z6IExF9MWei6OKaudHqvgvfw',
    appId: '1:48332235607:web:86c1f79164c3d9df809412',
    messagingSenderId: '48332235607',
    projectId: 'realtime-answerdetector',
    authDomain: 'realtime-answerdetector.firebaseapp.com',
    storageBucket: 'realtime-answerdetector.firebasestorage.app',
    measurementId: 'G-K8B2FBEHSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-weJeuC4X0JJkAaWddO_OEER4UN7F3bI',
    appId: '1:48332235607:android:471c23e251560511809412',
    messagingSenderId: '48332235607',
    projectId: 'realtime-answerdetector',
    storageBucket: 'realtime-answerdetector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5iSt2mzIx_HbGwNt5mqcqZ6WqYwTG_PA',
    appId: '1:48332235607:ios:c7c8be046a65413c809412',
    messagingSenderId: '48332235607',
    projectId: 'realtime-answerdetector',
    storageBucket: 'realtime-answerdetector.firebasestorage.app',
    iosBundleId: 'com.example.realtimeAnswerDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5iSt2mzIx_HbGwNt5mqcqZ6WqYwTG_PA',
    appId: '1:48332235607:ios:c7c8be046a65413c809412',
    messagingSenderId: '48332235607',
    projectId: 'realtime-answerdetector',
    storageBucket: 'realtime-answerdetector.firebasestorage.app',
    iosBundleId: 'com.example.realtimeAnswerDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD23QwVV32z6IExF9MWei6OKaudHqvgvfw',
    appId: '1:48332235607:web:2b974b66959556ac809412',
    messagingSenderId: '48332235607',
    projectId: 'realtime-answerdetector',
    authDomain: 'realtime-answerdetector.firebaseapp.com',
    storageBucket: 'realtime-answerdetector.firebasestorage.app',
    measurementId: 'G-WS662YG5HH',
  );
}
